# -*- coding: utf-8 -*-
"""DAY_029_HW

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ov1o9hmM9AJq1ePshho9ozJ7bKZEIdLn
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import math
import statistics
import seaborn as sns

men = pd.Series([164, 175, 183, 173, 176,
                159, 165, 165, 169, 151,
                156, 163, 169, 144, 170,
                177, 165, 160, 164, 171])
women = pd.Series([169, 170, 162, 154, 183,
                  173, 169, 167, 170, 185,
                  162, 175, 168, 151, 181,
                  170 ,182, 156, 159, 160])

print(men.describe())
print(women.describe())